# .travis.yml

language: bash
script:
  - ./test.sh
notifications:
  email: false
  slack:
    secure: IMnjDwTFTQC6KBjiae/4EgBa30tAe9g/RTBpSfuwRuzCVJVoRQVAqRncRPf1A1x0FSXjNZXDfA5tZDkDxpDj8VlY8fhBU4rLy3MGYR9anRSzDOvNczp1vO+ikfVweXIhZ5i558eYAxtryQGg2z41HwlCxhH9gU4K70EvwwKfP2Q3z0Xj2rfj6WrpnqkQmRxPZa9kkVPwoBDuth/BJj42RIBLMhVS+PCiy95mkQnA0ITt4VMC9+jROQIJUdgwxCeO97oIkYEoddnAhhsSfUyi0KjsyKf75v18c1tHxLrjikRjHdsL+vrFqwgpsoPDY0A/DDI2oZzv4C8r5K3ScQ7JMSJqIxqfG5sXbRp1j4wX9VGqFI7UJ1NbsobSKjY/RQzO/e/Fd0AMeah6pKDQZ54KCVNLfC/pstBJGKE+Mw2zR1OHoySLB7+K0riHEf7GuFExaGnjeWI9oEIlZsESysE0+Cjc7h04BeAox+7fMru/+v3fRdbgiNlxBm/K7B0dhRDAuqceXzeyJkmLuy9LZ7W5Cj25AcesUGyvaHQc7hfPGLbdconKM50+HPtzOmOAatsC+ccvA1giS47YR3Avt6cHSM2VkKMySUBvvsbiwKqfzZTGoj6WUwqBqtsgQ7s5sLJ9RiJLAHBF14dB0zpsDeN1ra66JWX+v/ujBGFwgjCUUgM=
